# Generated by Django 5.1.1 on 2024-09-24 02:01

import django.db.models.deletion
import listings.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('CHAIR', 'Chair'), ('TABLE', 'Table'), ('SOFA', 'Sofa'), ('BED', 'Bed'), ('DRESSER', 'Dresser'), ('BOOKSHELF', 'Bookshelf'), ('DESK', 'Desk'), ('CABINET', 'Cabinet'), ('WARDROBE', 'Wardrobe'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('new_with_tags', 'New with tags'), ('new_without_tags', 'New without tags'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('in_progress', 'In Progress'), ('completed', 'COMPLETED')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_comments', models.ManyToManyField(related_name='comments', through='listings.Comment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FurnitureListings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.furniturelisting'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=listings.models.listing_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.furniturelisting')),
            ],
        ),
    ]
