# Generated by Django 5.1.1 on 2024-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniturelisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'COMPLETED')], default='draft', max_length=20),
        ),
    ]
