# Generated by Django 5.1.1 on 2024-09-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_furniturelisting_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniturelisting',
            old_name='user',
            new_name='seller',
        ),
    ]
