# Generated by Django 5.1.1 on 2024-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_user_furniturelisting_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='listingimage',
            unique_together={('listing', 'order')},
        ),
    ]
