# Generated by Django 5.1.3 on 2024-12-05 15:01

import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_furniturelisting_status_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniturelisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('new_with_tags', 'New with tags'), ('new_without_tags', 'New without tags'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='furniturelisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furniturelisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[listings.models.validate_positive_or_none]),
        ),
        migrations.AlterField(
            model_name='furniturelisting',
            name='public_comments',
            field=models.ManyToManyField(blank=True, related_name='comments', through='listings.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='furniturelisting',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
