# Generated by Django 5.1.3 on 2024-12-15 11:15

import listings.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_furniturelisting_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=listings.models.CompressedImageField(upload_to=listings.models.listing_path),
        ),
    ]
