# Generated by Django 5.1.1 on 2024-09-30 14:50

import listings.models
import storages.backends.s3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingimage_options_listingimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail',
            field=listings.models.CompressedImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=listings.models.listing_path),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=listings.models.CompressedImageField(storage=storages.backends.s3.S3Storage(), upload_to=listings.models.listing_path),
        ),
    ]
