# Generated by Django 5.1.1 on 2024-10-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingimage_thumbnail_alter_listingimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='thumbnail',
        ),
    ]
